global TILE_SIZE <const> = 32
global PIPE_SIZE <const> = TILE_SIZE / 2
global BACKGROUND_SPEED <const> = 0.03
global PIPE_SPEED_RATIO <const> = 2
global PIPE_SPEED <const> = BACKGROUND_SPEED * PIPE_SPEED_RATIO
global INVULNERABLE_TIME <const> = 2000
-- how fast do the bubbles move back to the center?
global BUBBLE_RESTORATION_SPEED <const> = 0.02
global BUBBLE_TARGET_Y <const> = 200
global SPRITE_STRIDE <const> = 32

